---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liu.
--- DateTime: 2025/11/8 13:52
---
local key = KEYS[1]
local expireSeconds = tonumber(ARGV[1])

if redis.call("TTL", key) == -1 then
    -- 如果没有设置过期时间
    redis.call("EXPIRE", key, expireSeconds)
end
local result = redis.call("INCR", key)
return result