---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liu.
--- DateTime: 2025/10/15 14:15
---
local key = KEYS[1]
local defaultValue = tonumber(ARGV[1])
local expireSeconds = tonumber(ARGV[2])

local value = redis.call("GET", key)
-- Redis不存在，设置初始值为defaultValue，并设置过期时间ttl
local num = defaultValue + 1
redis.call("SET", key, num, "EX", expireSeconds)
return num